#! /usr/bin/perl
#
# This is a Perl script used to convert the Icarus Wing source to latex

while (<>) {

    s/_(\w+)_/{\\it \1}/;			# convert _ to italics
    s/_/ /g;					# convert interior _ to spaces

    s/^(\w+):(.*)"(.*)"/\2 \\textcolor{\1}{"\3"}/g;

    print;

}
