#! /usr/bin/perl
#
# This is a Perl script used to convert the Icarus Wing source to latex

my $speaker;
my $counter = 0;

sub ProcessLine {

    s/\$/\\\$/;				# quote $

    s/_([\w'!]+)_/{\\it \1}/;		# convert _ to italics
    s/_/ /g;				# convert interior _ to spaces

    # The speaking character can be indicated by a notation at the
    # beginning of the line or paragraph like "Alister:".  Note
    # if this is the case, or undef $speaker if we're at a blank
    # line (in between paragraphs)

    $speaker=$1 if (/^(\w+):/);
    undef $speaker if (/^$/);
    $counter=0 if (/^$/);

    # Remove speaker indication now that we've processed it.
    s/^(\w+)://;

    # Set text color for material in quotes according to speaker
    # Actual colors are defined above in the LaTeX preamble.

    while (/"/ and defined $speaker) {
	if ($counter % 2 == 0) {
	    s/"/\\textcolor{$speaker}{``/;
	} else {
	    s/"/''}/;
	}

	$counter ++;
    }

    print;
}

sub ProcessFile {
    my ($FILE) = @_;

    while (<$FILE>) {
	my $filename = $_;
	chomp $filename;

	if (-r $filename) {
	    open(NESTED_FILE, "<$filename");
	    ProcessFile(\*NESTED_FILE);
	    close(NESTED_FILE);
	} else {
	    ProcessLine;
	}
    }
}

print q|

\documentclass{book}

\usepackage{vmargin}
\usepackage{times}
\usepackage[pdftex]{color}

\pdfinfo{
  /Title	(Icarus' Wing)
  /Author	(Brent Baccala)
}

\begin{document}

\parindent 0pt
\parskip 12pt

% default seems to be 10/12
\fontsize{12pt}{14pt}
\selectfont

\title{Icarus' Wing}
\author{Brent Baccala}
\date{}

% No title page for e-reader version
% \maketitle

\definecolor{Bible}{rgb}{0.7,0,0}

\definecolor{Mercuriou}{rgb}{0.4,0.2,0}
\definecolor{Burns}{rgb}{0.3,0.3,0}
\definecolor{Vic}{rgb}{0.4,0,0.4}
\definecolor{Alister}{rgb}{0,0.4,0}
\definecolor{Andrea}{rgb}{0,0,0.4}

\definecolor{Kyle}{rgb}{0,0,0}

\definecolor{Ecks}{rgb}{0,0,0}
\definecolor{Wye}{rgb}{0,0,0}
\definecolor{Zee}{rgb}{0,0,0}

\definecolor{Beth}{rgb}{0,0,0}
\definecolor{James}{rgb}{0,0,0}
\definecolor{Jill}{rgb}{0,0,0}

\definecolor{Husband}{rgb}{0,0,0}

\frontmatter

\begin{center}
{\Huge Icarus' Wing}
\vskip 0.5in {\Large Brent Baccala}
\end{center}

\mainmatter

|;

ProcessFile(\*STDIN);

print q|
\end{document}
|;
